### ISSUE TITLE
Email feature needed

### ISSUE THREAD

**Issue by angelflo** [limegrow/ingenico-m2-payments#12]
Hi,

Is it possible to implement a feature to send confirmation email ONLY after payment DONE ?
Some of your competitor like payplug also have this feature in the backend management and this feature is really usefull because currently with your extension customer receive confirmation email when he leave the website to finalise the payment on your platform so it mean that it rceive confirmation email before the payment and it create misunderstanding.

Thanks a lot

**Comment by olegisk** [comment]
@angelflo Hello. What kind of confirmation email do you mean? Would be good if you could attach screenshot.
Actually, our extension has some option which allows control the behavior of confirmation sending.
![Screenshot123](https://user-images.githubusercontent.com/871275/116269666-3a522500-a7a0-11eb-80e7-1f7c166d002d.png)

**Comment by angelflo** [comment]
Thanks a lot for your prompt reply.
Sorry but I need clarification because I'm french customer of Ingenico
Ogone and when i had speak with our commercial to have more info about
epayments offers they told me that this solution is only for BIG companies
wiht more than 10 millions and that company like mine with 1 million can
only have access to Ogone solution ... (honestly this division of your
offers is more and more difficult to understand for the e-merchants)
so currently in my config i had flag this Epayment (Generic method) method
is ENABLE = NO
and I have ONLY enable :
- Credit Card
- Carte Bancaire
For both, i don't have this param to trigger the confirmation email when
status becomes 'Processing'

Is it a misunderstanding in my side ... and can I enable the Epayment
generic method ?
or do you confirm that epayment is a special offer of ingenico only
available for the major big companies ?
and in that case how to have this feature for the Credit Card and Carte
Bancaire case ?

Thanks


Le mar. 27 avr. 2021 à 17:34, Oleg Iskusnyh ***@***.***> a
écrit :

**Comment by olegisk** [comment]
@angelflo Don't pay attention to "Ingenico e-payments" section. Such paramters like these are common for all payment method there. I think we should move it to somewhere to avoid confusion.
You can leave "NO" for this payment method. These option will affect  "Credit Card" and "Carte Bancaire" also

cc: @raidoa

**Comment by angelflo** [comment]
Hi,

I do some test with the fields you send me in your previous answer :
New order Status : Pending
Suppress order confirmation email : No
Order status who triggers an order confirmation : Processing

But with this config, the confirmation email is still send to customer
immediately after the redirect to ingenico payment page (and so before the
payment).

Any suggestion ?

Thanks

Le mar. 27 avr. 2021 à 18:24, Oleg Iskusnyh ***@***.***> a
écrit :

**Comment by olegisk** [comment]
@angelflo Try to set follow:
New order Status : Pending
Suppress order confirmation email : Yes
Order status who triggers an order confirmation : Processing

And set follow:
![ScreenshotZ](https://user-images.githubusercontent.com/871275/116511517-5fea4600-a8e8-11eb-8b8d-56a47a9588b6.png)
