### ISSUE TITLE
sales_order_save_commit_after Event fired twice

### ISSUE THREAD

**Issue by choussamaster** [limegrow/ingenico-m2-payments#17]
Hi
the module is firing the event sales_order_save_commit_after twice, 
First on 
Processor.php:271, Ingenico\Payment\Model\Processor->processOrderPayment()
And second on
Processor.php:296, Ingenico\Payment\Model\Processor->processOrderPayment()
this makes the behavior of all scripts that map to this observer obsolete
Order has to be saved before the invoice save or avoid a second save on order

**Comment by olegisk** [comment]
@choussamaster Thanks for reporting! We will fix it the next release

**Comment by olegisk** [comment]
@choussamaster Hi, this issue has been fixed in v2.9.1. Please update
