### ISSUE TITLE
Saving PSPID on store level throws exception.

### ISSUE THREAD

**Issue by homanp** [limegrow/ingenico-m2-payments#2]
Saving the PSPID value on a specific store throws an exception in Magento admin:

`Exception #0 (Exception): Notice: Undefined index: value in /var/www/dom-magento/vendor/ingenico/m2-payment/Plugin/MagentoConfigControllerAdminhtmlSystemConfigSave.php on line 124`

We are running Magento ver. 2.3.5-p1.

**Comment by raidoa** [comment]
Hi,

Having multiple stores?

**Comment by homanp** [comment]
Yes, exactly

**Comment by homanp** [comment]
@raidoa any ETA on a fix?

**Comment by raidoa** [comment]
@homanp Multiple stores is not fully supported yet. There is a possibility that this support will be added but it will be decided in the upcoming weeks.

**Comment by raidoa** [comment]
This issue should be solved with the latest release. Closing for now.
