### ISSUE TITLE
Error: Undefined class constant 'CORE_CODE'

### ISSUE THREAD

**Issue by bramstroker** [limegrow/ingenico-m2-payments#23]
On cancelling an order in Magento the following error will arise when the order was made using another payment method than one of the Ingenico methods.
`Error: Undefined class constant 'CORE_CODE'`

This issue originates at https://github.com/limegrow/ingenico-m2-payments/blob/master/Model/Connector.php#L1251.

Here the constant `CORE_CODE` is directly called, but this constant is part of the ingenico module and only available on Ingenico payment methods, so this will result in a fatal error when calling on a payment method from another PSP.

This same problem can happen in `getQuotePaymentMethod`, and maybe other places.

There are also several code smells in this method.
- Calling a constant on a `MethodInterface` instance, but this is not part of the contract.
- No typehinting and return types
- Order payment could potentially be null, resulting in a error
- Catching exception and not logging anything (thus silencing any errors)

The "clean" fix imo would be to add a method `getCoreCode()` (not sure what this code is anyway) to `AbstractMethod`, of better yet introduce a interface for this.

Than the method `getOrderPaymentMethod` can be refactored like this:

```php
public function getOrderPaymentMethod($orderId)
{
    try {
        $order = $this->processor->getOrderByIncrementId($orderId);
        $method = $order->getPayment()->getMethodInstance();
        if ($method instanceof AbstractMethod) {
            return $method->getCoreCode();
        } else {
            return $method->getCode();
        }
    } catch (\Exception $exception) {
        return false;
    }
}
```

**Comment by olegisk** [comment]
@bramstroker Thank you for your comment. I think we can refactor it in the future.
Btw, do you think somebody will use `getOrderPaymentMethod()` for non-Ingenico orders? :-)

**Comment by bramstroker** [comment]
Well it is called for non ingenico orders, that's why I create this issue in the first place, as it breaks the cancel flow at the moment.

The ingenico module has an observer on `order_cancel_after`. Which will trigger the following calls.
- `CancelPaymentAuthorisation::execute`
- `IngenicoClient\IngenicoCoreLibrary::cancel`
- `IngenicoClient\IngenicoCoreLibrary::getOrder`
- `IngenicoClient\ConnectorInterface::getOrderPaymentMethod`

Nowhere in this flow is checked that the particular order is payed with Ingenico.

This could potentially be a problem not only with the cancel flow, because the method `IngenicoClient\IngenicoCoreLibrary::getOrder` is called from a lot of places.

**Comment by olegisk** [comment]
@bramstroker Thank you very much. We will fix it

**Comment by bramstroker** [comment]
Thanks for the quick headsup

**Comment by bramstroker** [comment]
@olegisk Any update on this one?
