### ISSUE TITLE
Inline Payment Form returns empty page with Javascript

### ISSUE THREAD

**Issue by bobarres** [limegrow/ingenico-m2-payments#34]
Hi,

since two days (around 05./06.04.2022) almost no cc transactions are going through to ingenico for none of our 7 PSPIds.

After submitting the CC card data via inline payment form, it returns a javascript in the iframe that doesn't execute so the checkout stays unfinished:

<html><head><script type="application/javascript">
                        window.onload = function() {
                            top.jQuery("body").trigger(
                                "ingenico:inline:success",
                                ["XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", "VISA"]
                            );
                        };
                    </script></head><body></body></html>

To transaction in log, none in ingenico backend.

Ingenico support tells us to contact support @ limegrow. Unfortunetaly this is a serious problem.

We did'nt do any changes to magento or the ingenico integration whatsoever.

Thanks for your help

Robert

**Comment by olegisk** [comment]
@bobarres Hi, i will take a look at this problem. Could you contact with me oleg@iskusnyh.pro please?

**Comment by bobarres** [comment]
Hi Oleg, 
thanks for your feedback. Fortunately the problem seems to be solved - there was a jQuery version conflict with one of our Google Tag Manager Intergations. As a result the window load function from within the iframe did not work anymore. After disabling the erroneous script, my test order was passed correctly. I will watch if the conversions get back to normal.
Sorry for the confusion.
Best regards Robert
