### ISSUE TITLE
iDeal bank selection difficulties on 2.6.3

### ISSUE THREAD

**Issue by lphilippo** [limegrow/ingenico-m2-payments#9]
Hello,

We have been testing release 2.6.3, which includes a bank selection for the iDeal method on the checkout page, on a Magento 2.4.2 installation.

We have encountered various issues that we hope can be resolved. Although our environment uses a common OSC module, the explanation below feels broader than a specific environment configuration issue.

- When we select the iDeal payment method option, the payment data is being set in `js/view/payment/method-renderer/abstract.js`, more specifically by the implementation of `getData()`. It seems that this function (sometimes) triggers just before the `_active` class is being added to the payment-method DOM element, which causes:
```
$('.payment-method._active [name="payment[issuer_id]"]').val(),
```
to fail. As we're here in the context of `ingenico_ideal` already, it seems a safe option to use:
```
$('#payment_form_ingenico_ideal [name="payment[issuer_id]"]').val()
```
Or more generic, `'#payment_form_' + this.getCode()`, instead of `payment-method._active`

- Since the empty `issuer_id` was still present in the payload, the XHR call for the payments would eventually fail in the `validate` function of `\Ingenico\Payment\Model\Method\Ideal'. Unfortunately, the exception class `CouldNotSaveException` is not included in the class dependencies, so a PHP error is thrown, instead of a controlled exception. This is easily resolved by including:
```
use Magento\Framework\Exception\CouldNotSaveException;
```

- The final issue  occurs we select `iDeal` as the default payment option. The payment method correctly show "selected" on the checkout page, but the first XHR call for payments then includes the following payload:
```
"paymentMethod": {
    "additional_data":null,
    "method":"ingenico_ideal",
    "po_number":null
}
```
Because there is no `issuer_id` present, the user will directly see the error message "Please select bank" . This is of course unwanted behaviour, as the first option of the dropdown is filled by default. We were not yet able to determine the exact cause or resolution, but this payload has its origin in `magento/module-checkout/view/frontend/web/js/view/payment/default.js`.

Are you able to confirm the issues and the solution of the first two items, and able to simulate the last one? If we can provide any additional information, please let us know.

**Comment by olegisk** [comment]
@lphilippo Thank you for detailed bug report!
We have fixed issues related to iDeal feature and we are going to make new release very soon.

**Comment by lphilippo** [comment]
@olegisk That's good to hear! We will re-test the described steps as soon as we see the release. However, are you able to confirm if you recognize the behaviour when `iDeal` has been selected as the default payment method (the third point)? If so, we will hold off looking into this one more thoroughly, until the release has been done.

**Comment by lphilippo** [comment]
Hello @olegisk 

We have just tried the various scenarios on release 2.7.0 and all of them can be marked as resolved.

Thanks for the good work!
